// Admin console i18n labels — bilingual (en/zh)
// Pattern: adminLabels.ts from 管理后台国际化.md spec

export type AdminLang = 'en' | 'zh';

const LANG_KEY = 'admin_lang';

export function getAdminLang(): AdminLang {
  if (typeof window === 'undefined') return 'en';
  return (localStorage.getItem(LANG_KEY) as AdminLang) || 'en';
}

export function setAdminLang(lang: AdminLang): void {
  localStorage.setItem(LANG_KEY, lang);
}

export const labels: Record<AdminLang, Record<string, string>> = {
  en: {
    // ===== Common =====
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    no_data: 'No data',
    confirm_delete: 'Confirm Delete',
    delete_confirm_message: 'Are you sure? This action cannot be undone.',
    logout: 'Logout',
    edit: 'Edit',
    archive: 'Archive',
    close: 'Close',
    all: 'All',
    search_placeholder: 'Search...',

    // ===== Navigation =====
    brand: 'Pipeline',
    nav_group_operations: 'OPERATIONS',
    nav_group_content: 'CONTENT',
    nav_group_management: 'MANAGEMENT',
    nav_dashboard: 'Dashboard',
    nav_pipeline: 'Pipeline',
    nav_queue: 'Queue',
    nav_published: 'Published',
    nav_sources: 'Sources',
    nav_settings: 'Settings',

    // ===== Login =====
    login_title: 'Pipeline Admin',
    login_placeholder: 'Access token',
    login_error: 'Invalid credentials',
    login_connect_error: 'Connection failed',
    login_btn: 'Enter',
    login_loading: '...',

    // ===== Dashboard =====
    dash_title: 'Dashboard',
    pending_review: 'Pending Review',
    pending_analysis: 'Pending Analysis',
    approved: 'Approved',
    published: 'Published',
    rejected: 'Rejected',
    total: 'Total',
    avg_score: 'Avg Score',
    sources_summary: 'Sources',
    sources_total: 'Total',
    sources_active: 'Active',
    sources_pending: 'Pending',
    discovery_runs: 'Runs',
    status_distribution: 'Status Distribution',
    recent_runs: 'Recent Activity',
    no_runs: 'No runs yet',
    review_candidates: 'Review {n} candidates',
    channel: 'Channel',
    date: 'Date',
    found: 'Found',
    new_col: 'New',
    status: 'Status',

    // Dashboard — analytics
    pipeline_funnel: 'Pipeline Funnel',
    discovered: 'Discovered',
    analyzed: 'Analyzed',
    reviewed: 'Reviewed',
    translated: 'Translated',
    conversion: 'conversion',
    category_distribution: 'Category Distribution',
    score_distribution: 'Score Distribution',
    score_low: 'Low (<5)',
    score_medium: 'Medium (5-7)',
    score_high: 'High (≥7)',
    top_sources: 'Top Sources',
    approval_rate: 'Approval',
    candidates_col: 'Candidates',

    // ===== Pipeline =====
    pipeline_title: 'Pipeline Monitor',
    pipeline_stages: 'Pipeline Stages',
    stage_discover: 'Discover',
    stage_analyze: 'Analyze',
    stage_translate: 'Translate',
    stage_publish: 'Publish',
    stage_health: 'Health Check',
    last_run: 'Last run',
    pending_items: 'pending',
    run_history: 'Run History',
    duration: 'Duration',
    errors: 'Errors',
    duplicates: 'Duplicates',
    no_errors: 'No errors',
    filter_channel: 'Filter by channel',

    // ===== Queue =====
    queue_title: 'Review Queue',
    candidates_count: '{n} candidates',
    selected_count: '{n} selected',
    batch_approve: 'Approve All',
    batch_reject: 'Reject All',
    source_path: 'Source / Path',
    summary: 'Summary',
    score: 'Score',
    category: 'Category',
    ai_rec: 'AI',
    prev: 'Prev',
    next: 'Next',
    page_of: '{page} / {total}',
    no_candidates: 'No candidates found',
    search_candidates: 'Search by name, path, summary...',
    filter_source: 'All sources',

    // ===== Detail =====
    back_to_queue: 'Queue',
    source: 'Source',
    format: 'Format',
    tokens: 'Tokens',
    created: 'Created',
    approve: 'Approve',
    reject: 'Reject',
    tab_content: 'Content',
    tab_analysis: 'AI Analysis',
    tab_overrides: 'Overrides',
    no_analysis: 'No analysis available',
    save_overrides: 'Save Overrides',
    saving: 'Saving...',
    rejection_reason: 'Rejection reason (optional):',
    use_ai_suggestion: '— Use AI suggestion —',
    override_category: 'Category',
    override_type: 'Type',
    override_difficulty: 'Difficulty',
    override_tags: 'Tags (JSON array)',
    name_cn: 'Name (CN)',
    name_en: 'Name (EN)',
    highlight_cn: 'Highlight (CN)',
    highlight_en: 'Highlight (EN)',
    review_notes: 'Review Notes',
    relevance: 'Relevance',
    structure: 'Structure',
    actionability: 'Actionability',
    uniqueness: 'Uniqueness',
    completeness: 'Completeness',
    recommendation: 'Recommendation',
    tags: 'Tags',
    duplicate_of: 'Duplicate Of',
    rejection_label: 'Rejection Reason',
    difficulty: 'Difficulty',
    type: 'Type',

    // ===== Published =====
    published_title: 'Published Skills',
    published_count: '{n} published skills',
    name: 'Name',
    published_at: 'Published',
    pr_link: 'PR',
    no_published: 'No published skills yet',
    view_pr: 'View PR',

    // ===== Sources =====
    sources_title: 'Sources',
    add_source: '+ Add Source',
    repo_url: 'Repository URL',
    repo_id: 'ID (owner/repo)',
    skill_pattern: 'Skill Pattern',
    pattern: 'Pattern',
    candidates: 'Candidates',
    last_checked: 'Last Checked',
    via: 'Via',
    never: 'Never',
    adding: 'Adding...',
    add: 'Add Source',
    repository: 'Repository',
    approved_col: 'Approved',
    avg_score_col: 'Avg Score',
    notes: 'Notes',
    edit_source: 'Edit Source',
    source_stale: 'Stale',
    actions: 'Actions',

    // ===== Settings =====
    settings_title: 'Settings',
    system_info: 'System Information',
    table_name: 'Table',
    row_count: 'Rows',
    last_run_by_channel: 'Last Run by Channel',
    pipeline_version: 'Pipeline v0.1.0',
  },

  zh: {
    // ===== Common =====
    loading: '加载中...',
    save: '保存',
    cancel: '取消',
    delete: '删除',
    no_data: '暂无数据',
    confirm_delete: '确认删除',
    delete_confirm_message: '确定要删除吗？此操作不可撤销。',
    logout: '退出',
    edit: '编辑',
    archive: '归档',
    close: '关闭',
    all: '全部',
    search_placeholder: '搜索...',

    // ===== Navigation =====
    brand: 'Pipeline',
    nav_group_operations: '运营',
    nav_group_content: '内容',
    nav_group_management: '管理',
    nav_dashboard: '仪表盘',
    nav_pipeline: '流水线',
    nav_queue: '审核队列',
    nav_published: '已发布',
    nav_sources: '来源管理',
    nav_settings: '设置',

    // ===== Login =====
    login_title: '管理后台',
    login_placeholder: '访问令牌',
    login_error: '凭证无效',
    login_connect_error: '连接失败',
    login_btn: '进入',
    login_loading: '...',

    // ===== Dashboard =====
    dash_title: '仪表盘',
    pending_review: '待审核',
    pending_analysis: '待分析',
    approved: '已通过',
    published: '已发布',
    rejected: '已拒绝',
    total: '总计',
    avg_score: '平均分',
    sources_summary: '来源',
    sources_total: '总数',
    sources_active: '活跃',
    sources_pending: '待处理',
    discovery_runs: '运行次数',
    status_distribution: '状态分布',
    recent_runs: '最近活动',
    no_runs: '暂无运行记录',
    review_candidates: '审核 {n} 个候选',
    channel: '渠道',
    date: '日期',
    found: '发现',
    new_col: '新增',
    status: '状态',

    // Dashboard — analytics
    pipeline_funnel: '流水线漏斗',
    discovered: '已发现',
    analyzed: '已分析',
    reviewed: '已审核',
    translated: '已翻译',
    conversion: '转化',
    category_distribution: '分类分布',
    score_distribution: '评分分布',
    score_low: '低分 (<5)',
    score_medium: '中分 (5-7)',
    score_high: '高分 (≥7)',
    top_sources: '来源排名',
    approval_rate: '通过率',
    candidates_col: '候选数',

    // ===== Pipeline =====
    pipeline_title: '流水线监控',
    pipeline_stages: '流水线阶段',
    stage_discover: '发现',
    stage_analyze: '分析',
    stage_translate: '翻译',
    stage_publish: '发布',
    stage_health: '健康检查',
    last_run: '最后运行',
    pending_items: '待处理',
    run_history: '运行历史',
    duration: '耗时',
    errors: '错误',
    duplicates: '重复',
    no_errors: '无错误',
    filter_channel: '按渠道筛选',

    // ===== Queue =====
    queue_title: '审核队列',
    candidates_count: '{n} 个候选',
    selected_count: '已选 {n} 个',
    batch_approve: '全部通过',
    batch_reject: '全部拒绝',
    source_path: '来源 / 路径',
    summary: '摘要',
    score: '评分',
    category: '分类',
    ai_rec: 'AI',
    prev: '上一页',
    next: '下一页',
    page_of: '{page} / {total}',
    no_candidates: '未找到候选',
    search_candidates: '搜索名称、路径、摘要...',
    filter_source: '所有来源',

    // ===== Detail =====
    back_to_queue: '队列',
    source: '来源',
    format: '格式',
    tokens: '令牌数',
    created: '创建时间',
    approve: '通过',
    reject: '拒绝',
    tab_content: '内容',
    tab_analysis: 'AI 分析',
    tab_overrides: '覆盖',
    no_analysis: '暂无分析结果',
    save_overrides: '保存覆盖',
    saving: '保存中...',
    rejection_reason: '拒绝原因（可选）：',
    use_ai_suggestion: '— 使用 AI 建议 —',
    override_category: '分类',
    override_type: '类型',
    override_difficulty: '难度',
    override_tags: '标签 (JSON 数组)',
    name_cn: '中文名称',
    name_en: '英文名称',
    highlight_cn: '中文亮点',
    highlight_en: '英文亮点',
    review_notes: '审核备注',
    relevance: '相关性',
    structure: '结构',
    actionability: '可操作性',
    uniqueness: '独特性',
    completeness: '完整性',
    recommendation: '建议',
    tags: '标签',
    duplicate_of: '重复项',
    rejection_label: '拒绝原因',
    difficulty: '难度',
    type: '类型',

    // ===== Published =====
    published_title: '已发布技能',
    published_count: '{n} 个已发布技能',
    name: '名称',
    published_at: '发布时间',
    pr_link: 'PR',
    no_published: '暂无已发布技能',
    view_pr: '查看 PR',

    // ===== Sources =====
    sources_title: '来源管理',
    add_source: '+ 添加来源',
    repo_url: '仓库地址',
    repo_id: 'ID (owner/repo)',
    skill_pattern: '技能匹配模式',
    pattern: '匹配模式',
    candidates: '候选数',
    last_checked: '最后检查',
    via: '发现方式',
    never: '从未',
    adding: '添加中...',
    add: '添加来源',
    repository: '仓库',
    approved_col: '已通过',
    avg_score_col: '平均分',
    notes: '备注',
    edit_source: '编辑来源',
    source_stale: '停滞',
    actions: '操作',

    // ===== Settings =====
    settings_title: '设置',
    system_info: '系统信息',
    table_name: '数据表',
    row_count: '行数',
    last_run_by_channel: '各渠道最后运行',
    pipeline_version: 'Pipeline v0.1.0',
  },
};
