/**
 * Creates a GitHub PR with translated skills, registry updates, and sources.yaml changes.
 */

import * as github from '../utils/github-api.js';
import * as db from '../db/client.js';
import { generatePublicationPackage } from './file-generator.js';
import type { PublicationPackage } from './file-generator.js';

const REPO_OWNER = process.env.GITHUB_REPO_OWNER || 'xcodethink';
const REPO_NAME = process.env.GITHUB_REPO_NAME || 'dl-skills-web';

/**
 * Create a PR with all translated skills ready for publication.
 */
export async function createPublicationPR(): Promise<{
  prNumber: number;
  prUrl: string;
  filesAdded: number;
  skillsAdded: number;
} | null> {
  const pkg = await generatePublicationPackage();

  if (pkg.files.length === 0) {
    console.log('No translated candidates ready for publication.');
    return null;
  }

  console.log(`Preparing PR with ${pkg.files.length} files (${pkg.candidateIds.length} skills)...`);

  // Get main branch SHA
  const mainSha = await github.getLatestCommitSha(REPO_OWNER, REPO_NAME, 'main');
  if (!mainSha) throw new Error('Could not get main branch SHA');

  // Create branch
  const date = new Date().toISOString().slice(0, 10);
  const branchName = `auto/add-skills-${date}-${pkg.candidateIds.length}`;

  const created = await github.createBranch(REPO_OWNER, REPO_NAME, branchName, mainSha);
  if (!created) throw new Error(`Could not create branch ${branchName}`);
  console.log(`Created branch: ${branchName}`);

  // Push files
  for (const file of pkg.files) {
    const ok = await github.createOrUpdateFile(
      REPO_OWNER, REPO_NAME, file.path, file.content,
      `Add skill: ${file.path}`, branchName
    );
    if (!ok) console.warn(`  Warning: failed to push ${file.path}`);
    else console.log(`  Pushed: ${file.path}`);
  }

  // Build PR body
  const body = buildPRBody(pkg);

  // Create PR
  const pr = await github.createPullRequest(
    REPO_OWNER, REPO_NAME,
    `Add ${pkg.candidateIds.length} new skills (${date})`,
    body,
    branchName,
    'main'
  );

  if (!pr) throw new Error('Failed to create PR');

  // Update candidate statuses in D1
  for (const id of pkg.candidateIds) {
    await db.execute(
      `UPDATE candidates SET
         status = 'publishing', pr_number = ?, pr_url = ?, updated_at = datetime('now')
       WHERE id = ?`,
      [pr.number, pr.url, id]
    );
  }

  console.log(`PR created: ${pr.url}`);

  return {
    prNumber: pr.number,
    prUrl: pr.url,
    filesAdded: pkg.files.length,
    skillsAdded: pkg.candidateIds.length,
  };
}

function buildPRBody(pkg: PublicationPackage): string {
  const skillTable = pkg.registryEntries.map(r => {
    const entry = r.entry as Record<string, any>;
    return `| ${r.key} | ${entry.unifiedCategory} | ${entry.type} | ${entry.difficulty} | ${entry.highlight_en || '—'} |`;
  }).join('\n');

  return `## Auto-generated Skill Publication

This PR adds **${pkg.candidateIds.length} new skills** discovered and translated by the pipeline.

### Skills Added

| Path | Category | Type | Difficulty | Summary |
|------|----------|------|------------|---------|
${skillTable}

### Files Changed

- ${pkg.files.length} content files (CN + EN pairs)
- Registry entries to be merged into \`data/skills-registry.yaml\`

### Notes

- All skills have been AI-analyzed with quality scores
- Translations are professional-grade (not machine-translation quality)
- Review the content before merging

---

*Generated by DL Skills Pipeline*`;
}
